### ISSUE TITLE
Trying to customize mailkick view

### ISSUE THREAD

**Issue by Borys216307** [ankane/mailkick#12]
I'm trying to customize the view generated by this command - "rails generate mailkick:views"
This command adds only view file(show.html.erb). Can you update the gem to generate the controller also? so I can use the layout of my own.

**Comment by tibetsprague** [comment]
I would also like this

**Comment by tibetsprague** [comment]
I did end up solving this by adding a file at `app/controllers/mailkick/subscriptions_controller.rb` that looks like this:

```
# Add a layout to Mailkick's subscriptions controller
# make sure mailkick's version is loaded before we re-open
load Mailkick::Engine.root.join('app/controllers/mailkick/subscriptions_controller.rb')
Mailkick::SubscriptionsController.class_eval do
  layout "application"
end
```

and then adding this to `initializers/mailkick.rb`:

```
# Make sure we load our customizations to the subscriptions controller
require 'mailkick/subscriptions_controller.rb'
```

**Comment by ankane** [comment]
Hey @tibetsprague, that sounds like a good solution. @Borys216307 not sure we want to generate the entire controller, but maybe we could add a `Mailkick.layout` option. Happy to review a PR.

**Comment by daveharris** [comment]
I just wanted to add a note here in case it helps someone else, in order to pull in some helpers but not the whole layout, inside `app/views/reminder_mailer/book.html.erb` you **can** (but maybe you shouldn't):

```erb
<%
  self.class_eval do
    include ApplicationHelper
  end
%>
```

It's a bit of a hack but it seems to work just fine.

It would be awesome if there was the ability to over-ride the controller like you can in Devise, but I have no idea how that is implemented under the covers:

```rb
devise_for :users,
  controllers: {
    sessions: 'sessions'
  }
```

**Comment by daveharris** [comment]
Is it worth add a few tips and tricks like the above and the use of `main_app.root_path` to the generating views section of the readme?
