### ISSUE TITLE
preventing emails from getting sent

### ISSUE THREAD

**Issue by taylor-a-barnette** [ankane/mailkick#30]
Is the gem intended to work with ActionMailer to prevent emails from being sent, or are we meant to wrap relevant calls in conditionals to prevent them from being sent? 

I've added the gem to an app and have followed the instructions provided in the readme. The db has the mailkick table; the views are present, etc. The unsubscribe link appears in emails and I am able to click it, visit the unsubscribe page, and unsubscribe. The 'active' attribute switches to true. Finally, I have 'mailkick_user' added to my User model. However, the app still sends emails. There is no difference between pre gem installation and post, save for a new table and new views.

**Comment by kyleschmolze** [comment]
This gem does not stop emails from being sent, you'll have to be the judge of that. Use the 
`User.opted_out` and `User.not_opted_out` methods to grab the right users, or prevent mail from sending by using the `user.opted_out?` method. 

It would be extremely aggressive for this gem to actually prevent emails from sending, because that can vary so hugely with different use cases. For example, should it stop "password reset" emails from sending, as well? Probably not, as I can't imagine any user asking for a password reset who doesn't want to receive that email, no matter whether or not they've unsubscribed in the past. How would Mailkick know which emails to stop, and which to let through? You'd have to code it in, and at that point, it's easiest to just provide a simple api which makes that easy. Code like this may be what you want:

```
User.not_opted_out.each{|user| MarketingMailer.send_marketing_email(user).deliver }

# or in MarketingMailer.rb:

def send_marketing_email(user)
  return if user.opted_out?
  mail to: user.email, subject: 'Buy our product!'
end
```

**Comment by taylor-a-barnette** [comment]
Appreciate you taking the time to type out the above, my friend. For future note if others find this: My original post stemmed from a misreading of the documentation, which had inclined me to assume that the gem stops emails from sending. If anyone happens to land in the same spot, this assumption is incorrect, and you can read the answer above from kyle for clarification.
