### ISSUE TITLE
Mailkick.secret_token is nil in Rails 5.2 app w/ legacy config.secret_token

### ISSUE THREAD

**Issue by joshuap** [ankane/mailkick#51]
We haven't upgraded to `config.secret_key_base` yet (but we have an empty config/secrets.yml file); our `Rails.application.config.secret_token` is still stored in config/initializers/secret_token.rb.

When I tried to use Mailkick, I got an error about a missing `Rails.application.config.secret_key_base`. It looks like [this line](https://github.com/ankane/mailkick/blob/aaee43e36fbf7674eafa42376d1c7b229f2d9d2f/lib/mailkick/engine.rb#L12) is evaluating to `true`, and then in [this line](https://github.com/ankane/mailkick/blob/aaee43e36fbf7674eafa42376d1c7b229f2d9d2f/lib/mailkick/engine.rb#L18), `creds.respond_to?(:secret_key_base)` evaluates to `true` when it should be `false` (it appears that `creds.respond_to?(:anything)` also evaluates to `true`).

**Comment by ankane** [comment]
Hey @joshuap, thanks for the report. That logic is a bit messy, but think it works for most cases since there are rarely reports, so I'd rather not change it since there's a risk it'll break other apps. It sounds like you're in the middle of upgrading which should be an uncommon state. You can also set `Mailkick.secret_token` if needed.

**Comment by joshuap** [comment]
@ankane yep, setting `Mailkick.secret_token` is how I ended up fixing this. Makes sense to me--I think this is an edge case caused by an empty secrets.yml existing during an upgrade. I just wanted to document it!
