### ISSUE TITLE
Support for Lockbox?

### ISSUE THREAD

**Issue by chuckphillips** [ankane/mailkick#54]
Any plans to support lockbox encryption of the `email` column in the `mailkick_opt_outs` table?

**Comment by ankane** [comment]
Hey @chuckphillips, I think you can add the necessary columns and create an initializer with:

```ruby
Mailkick::OptOut.encrypts :email
Mailkick::OptOut.blind_index :email
```

(and follow the typically pattern for migrating columns if needed)

This line will need to be changed use Active Record to generate email condition - something like `WHERE EXISTS(#{Mailkick::OptOut.where(email: email, ...).to_sql})` - so it'll use the blind index when one exists or the normal column otherwise.

https://github.com/ankane/mailkick/blob/4dad73629bfdc0d7c86a17276cfa6f9682ba444b/lib/mailkick/model.rb#L14

Let me know if you have any luck with it.

**Comment by ankane** [comment]
Cleaning up issues

**Comment by xdmx** [comment]
I just wanted to say that native support to Lockbox would be awesome :pray:

**Comment by ankane** [comment]
Just fyi: Just pushed Mailkick 1.0, which no longer stores emails (it just references models). This should be better for privacy.
