### ISSUE TITLE
[Rails 6] Advice for injecting manual connection switching for unsubscribe GET route

### ISSUE THREAD

**Issue by rromanchuk** [ankane/mailkick#55]
https://edgeguides.rubyonrails.org/active_record_multiple_databases.html#using-manual-connection-switching

Using Rails 6 multiple database support, the GET request attempts to use the reader role which then fails. Thinking about what the cleanest approach to wrapping `opt_out(options)` inside of a `ActiveRecord::Base.connected_to(role: :writing)` block. Right now i'm just monkey patching the controller action.

Similar issues in other gems https://github.com/heartcombo/devise/issues/5133

**Comment by ankane** [comment]
Hey @rromanchuk, you should be able to add an `around_action` for the controller in an initializer. Something like:

```ruby
Mailkick::SubscriptionsController.around_action do
  ActiveRecord::Base.connected_to(role: :writing) do
    yield
  end
end
```

Another approach could be customizing the resolver to exclude Mailkick paths.

The automatic connection switching feature is opt-in and pretty basic right now (by design), so I don't think it make sense to add official support for it.
