### ISSUE TITLE
Add endpoint to process bounces/spam in real time

### ISSUE THREAD

**Issue by xdmx** [ankane/mailkick#59]
Hey Andrew, it's me again :grin: 

Correct me if I'm wrong, at the moment the only way to sync bounces/spam email address and unsubscribe them in the app is through the `Mailkick.fetch_opt_outs`, which I guess it needs to be called in a cron on a daily/hourly basis. Is that right?

My worry about this is that with a big number of users there is also a risk of having many addresses to sync every time, and most of them would already be synced from the previous run.

Given that all services support a webhook/notification system to send in real time a request with the bounced/spam/unsubscribed addresses, have thought about adding an endpoint to process this requests and rely less on the `fetch_opt_outs` after the first run?

**Comment by ankane** [comment]
Hey @xdmx, that's another interesting idea, but probably shouldn't be needed for most applications. The batch job only updates records that need updated (and the current opt-out query can be optimized if performance becomes an issue). There could also be an option like `fetch_opt_outs(since: 1.day.ago)` that only fetches records after a specific time.

**Comment by ankane** [comment]
Cleaning up issues. This feature may go well with #58 if you decide to build it.
